language: java
jdk:
- oraclejdk8
script:
- bin/activator universal:packageZipTarball
deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  skip_cleanup: true
  file: target/universal/microservice-notifications-0.0.1.tgz
